# Generated by Django 4.2.4 on 2023-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_usuariostripe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariostripe',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
