# Generated by Django 4.2.4 on 2023-08-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_productoimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'verbose_name': 'Producto Imagen', 'verbose_name_plural': 'Productos Imagenes'},
        ),
    ]
