# Generated by Django 4.2.4 on 2023-09-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('titulo', 'slug')},
        ),
    ]
