# Generated by Django 4.2.4 on 2023-09-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_variacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacion',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.productoimagen'),
        ),
    ]
