# Generated by Django 4.2.4 on 2023-09-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_alter_producto_update_defaults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacion',
            old_name='categoria',
            new_name='variacion',
        ),
    ]
