# Generated by Django 4.2.4 on 2023-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_rename_categoria_variacion_variacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacion',
            options={'verbose_name': 'Variación', 'verbose_name_plural': 'Variaciones'},
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
