# Generated by Django 4.2.4 on 2023-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0006_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(blank=True, to='producto.producto')),
            ],
        ),
    ]
