# Generated by Django 4.2.4 on 2023-09-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_alter_carro_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='items',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='productos',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carro.carro'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='linea_total',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100),
        ),
    ]
