# Generated by Django 4.2.4 on 2023-09-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_productoimagen_imagen'),
        ('carro', '0005_remove_carro_items_remove_carro_productos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CarroItem',
        ),
    ]
