# Generated by Django 4.2.4 on 2023-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0006_rename_cartitem_carroitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carroitem',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
