# Generated by Django 4.2.4 on 2023-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_variacion_imagen'),
        ('carro', '0007_carroitem_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='carroitem',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='producto.variacion'),
        ),
    ]
