# Generated by Django 4.2.4 on 2023-09-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carro', '0009_remove_carroitem_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.CharField(default='abc', max_length=120, unique=True)),
                ('estado', models.CharField(choices=[('Started', 'started'), ('Abandoned', 'abandoned'), ('Finished', 'finished')], default='started', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.carro')),
            ],
        ),
    ]
