# Generated by Django 4.2.4 on 2023-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
