# Generated by Django 4.2.4 on 2023-09-26 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0002_alter_pedido_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
