# Generated by Django 4.2.4 on 2023-09-26 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_final_total_pedido_sub_total_pedido_tax_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
